[pytest]
testpaths = tests
python_files = test_*.py
addopts = -v --tb=short
filterwarnings =
    ignore:Type google\.protobuf:DeprecationWarning
    ignore:datetime\.datetime\.utcfromtimestamp:DeprecationWarning
    ignore:coroutine 'expire_cache' was never awaited:RuntimeWarning