"""tests/test_audio_contract.py — narration contract (change #12 + Phase 7).

Contract, per locale (en / zh-HK / zh-TW — the 7.5 completeness
strategy extended to audio):
  1. every exercise card and breathing practice in the LOCALE's data
     files carries an "audio" field resolving to an existing mp3, and
     the locale's audio directory holds exactly 29;
  2. the locale's manifest.json (written by tools/generate_audio.py
     --lang <loc>) covers every code;
  3. DRIFT GUARD (per language): each manifest text_sha256 equals the
     sha256 of the CURRENT locale instruction string — a copy change
     without regenerating the mp3 fails here;
  4. each manifest mp3_sha256 matches the file on disk.

EN keeps the TOP-LEVEL layout (assets/audio/{code}.mp3 — filenames are
contract); locales live in assets/audio/{lang}/ matching the locale
JSONs' audio paths. Locale audio is generated by `python
tools/generate_audio.py --lang zh-HK` (and zh-TW) — run generation
BEFORE this suite; a missing manifest/mp3 fails with a regeneration
hint.

mp3 CONTENT is unverifiable automatically; the manifest is the chain of
custody. Spot-listening remains a delivery-time manual QA line — now
per locale (rate -15% to start, per team decision).
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

from utils.assets import resolve_asset_path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
AUDIO_DIR = PROJECT_ROOT / "assets" / "audio"

LOCALES = ["en", "zh-HK", "zh-TW"]
EXPECTED_FILES = 29  # 24 exercise cards + 5 breathing practices, per locale


def _sha_text(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()


def _sha_file(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def _data_file(locale: str, base: str) -> Path:
    name = base if locale == "en" else base.replace(".json",
                                                    f".{locale}.json")
    return DATA_DIR / name


def _audio_dir(locale: str) -> Path:
    return AUDIO_DIR if locale == "en" else AUDIO_DIR / locale


def _cards(locale: str) -> list:
    with open(_data_file(locale, "exercise_cards.json"),
              encoding="utf-8") as f:
        return json.load(f)


def _practices(locale: str) -> list:
    with open(_data_file(locale, "breathing_sequences.json"),
              encoding="utf-8") as f:
        return json.load(f)["practices"]


def _manifest(locale: str) -> dict:
    path = _audio_dir(locale) / "manifest.json"
    assert path.is_file(), (
        f"missing {path} — run: python tools/generate_audio.py "
        f"--lang {locale}")
    return json.loads(path.read_text(encoding="utf-8"))


def _instruction_texts(locale: str) -> dict:
    texts = {c["card_id"]: c["instructions"] for c in _cards(locale)}
    texts.update({p["code"]: p["instruction"] for p in _practices(locale)})
    return texts


@pytest.mark.parametrize("loc", LOCALES)
def test_audio_fields_resolve(loc):
    problems = []
    for c in _cards(loc):
        if not c.get("audio"):
            problems.append(f"{c['card_id']}: missing 'audio' field")
        elif not resolve_asset_path(c["audio"]).is_file():
            problems.append(f"{c['card_id']}: {c['audio']} not found")
    for p in _practices(loc):
        if not p.get("audio"):
            problems.append(f"{p['code']}: missing 'audio' field")
        elif not resolve_asset_path(p["audio"]).is_file():
            problems.append(f"{p['code']}: {p['audio']} not found")
    assert not problems, "; ".join(problems)


@pytest.mark.parametrize("loc", LOCALES)
def test_audio_file_count(loc):
    mp3s = list(_audio_dir(loc).glob("*.mp3"))
    assert len(mp3s) == EXPECTED_FILES, (
        f"[{loc}] expected {EXPECTED_FILES} mp3s in {_audio_dir(loc)}, "
        f"found {len(mp3s)}: {sorted(m.name for m in mp3s)}")


@pytest.mark.parametrize("loc", LOCALES)
def test_manifest_covers_all_codes(loc):
    codes = set(_instruction_texts(loc))
    covered = set(_manifest(loc)) - {"_meta"}
    assert covered == codes, (
        f"[{loc}] manifest/code mismatch: "
        f"missing={sorted(codes - covered)}, "
        f"extra={sorted(covered - codes)}")


@pytest.mark.parametrize("loc", LOCALES)
def test_manifest_text_hashes_match_current_instructions(loc):
    """THE per-locale drift guard: copy changed but mp3 not regenerated
    -> stale."""
    manifest, texts = _manifest(loc), _instruction_texts(loc)
    stale = [code for code, text in texts.items()
             if manifest[code]["text_sha256"] != _sha_text(text)]
    assert not stale, (
        f"[{loc}] stale narration (instruction copy changed, mp3 not "
        f"regenerated) for: {stale} — run: python tools/generate_audio.py "
        f"--lang {loc} --filter {','.join(sorted(stale))}")


@pytest.mark.parametrize("loc", LOCALES)
def test_manifest_mp3_hashes_match_files(loc):
    manifest = _manifest(loc)
    mismatches = [code for code in set(manifest) - {"_meta"}
                  if manifest[code]["mp3_sha256"]
                  != _sha_file(_audio_dir(loc) / f"{code}.mp3")]
    assert not mismatches, (
        f"[{loc}] mp3 file does not match manifest "
        f"(replaced/edited?): {mismatches}")